/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.learn.calcite;

import org.junit.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(String greeting, String app_should_have_a_greeting) {
    }
}
